// Code generated by ent, DO NOT EDIT.

package channelhealthsample

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the channelhealthsample type in the database.
	Label = "channel_health_sample"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBucketTs holds the string denoting the bucket_ts field in the database.
	FieldBucketTs = "bucket_ts"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldSuccessCount holds the string denoting the success_count field in the database.
	FieldSuccessCount = "success_count"
	// FieldErrorCount holds the string denoting the error_count field in the database.
	FieldErrorCount = "error_count"
	// FieldRateLimitedCount holds the string denoting the rate_limited_count field in the database.
	FieldRateLimitedCount = "rate_limited_count"
	// FieldOverloadedCount holds the string denoting the overloaded_count field in the database.
	FieldOverloadedCount = "overloaded_count"
	// FieldLatencyP50Ms holds the string denoting the latency_p50_ms field in the database.
	FieldLatencyP50Ms = "latency_p50_ms"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the channelhealthsample in the database.
	Table = "channel_health_samples"
)

// Columns holds all SQL columns for channelhealthsample fields.
var Columns = []string{
	FieldID,
	FieldBucketTs,
	FieldAccountID,
	FieldGroupID,
	FieldModel,
	FieldSuccessCount,
	FieldErrorCount,
	FieldRateLimitedCount,
	FieldOverloadedCount,
	FieldLatencyP50Ms,
	FieldSource,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultSuccessCount holds the default value on creation for the "success_count" field.
	DefaultSuccessCount int
	// DefaultErrorCount holds the default value on creation for the "error_count" field.
	DefaultErrorCount int
	// DefaultRateLimitedCount holds the default value on creation for the "rate_limited_count" field.
	DefaultRateLimitedCount int
	// DefaultOverloadedCount holds the default value on creation for the "overloaded_count" field.
	DefaultOverloadedCount int
	// DefaultLatencyP50Ms holds the default value on creation for the "latency_p50_ms" field.
	DefaultLatencyP50Ms int
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ChannelHealthSample queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBucketTs orders the results by the bucket_ts field.
func ByBucketTs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBucketTs, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// BySuccessCount orders the results by the success_count field.
func BySuccessCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessCount, opts...).ToFunc()
}

// ByErrorCount orders the results by the error_count field.
func ByErrorCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCount, opts...).ToFunc()
}

// ByRateLimitedCount orders the results by the rate_limited_count field.
func ByRateLimitedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateLimitedCount, opts...).ToFunc()
}

// ByOverloadedCount orders the results by the overloaded_count field.
func ByOverloadedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOverloadedCount, opts...).ToFunc()
}

// ByLatencyP50Ms orders the results by the latency_p50_ms field.
func ByLatencyP50Ms(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatencyP50Ms, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
