// Code generated by ent, DO NOT EDIT.

package channelhealthsample

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLTE(FieldID, id))
}

// BucketTs applies equality check predicate on the "bucket_ts" field. It's identical to BucketTsEQ.
func BucketTs(v time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldBucketTs, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldAccountID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldGroupID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldModel, v))
}

// SuccessCount applies equality check predicate on the "success_count" field. It's identical to SuccessCountEQ.
func SuccessCount(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldSuccessCount, v))
}

// ErrorCount applies equality check predicate on the "error_count" field. It's identical to ErrorCountEQ.
func ErrorCount(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldErrorCount, v))
}

// RateLimitedCount applies equality check predicate on the "rate_limited_count" field. It's identical to RateLimitedCountEQ.
func RateLimitedCount(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldRateLimitedCount, v))
}

// OverloadedCount applies equality check predicate on the "overloaded_count" field. It's identical to OverloadedCountEQ.
func OverloadedCount(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldOverloadedCount, v))
}

// LatencyP50Ms applies equality check predicate on the "latency_p50_ms" field. It's identical to LatencyP50MsEQ.
func LatencyP50Ms(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldLatencyP50Ms, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldSource, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldCreatedAt, v))
}

// BucketTsEQ applies the EQ predicate on the "bucket_ts" field.
func BucketTsEQ(v time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldBucketTs, v))
}

// BucketTsNEQ applies the NEQ predicate on the "bucket_ts" field.
func BucketTsNEQ(v time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNEQ(FieldBucketTs, v))
}

// BucketTsIn applies the In predicate on the "bucket_ts" field.
func BucketTsIn(vs ...time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldIn(FieldBucketTs, vs...))
}

// BucketTsNotIn applies the NotIn predicate on the "bucket_ts" field.
func BucketTsNotIn(vs ...time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNotIn(FieldBucketTs, vs...))
}

// BucketTsGT applies the GT predicate on the "bucket_ts" field.
func BucketTsGT(v time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGT(FieldBucketTs, v))
}

// BucketTsGTE applies the GTE predicate on the "bucket_ts" field.
func BucketTsGTE(v time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGTE(FieldBucketTs, v))
}

// BucketTsLT applies the LT predicate on the "bucket_ts" field.
func BucketTsLT(v time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLT(FieldBucketTs, v))
}

// BucketTsLTE applies the LTE predicate on the "bucket_ts" field.
func BucketTsLTE(v time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLTE(FieldBucketTs, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLTE(FieldAccountID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLTE(FieldGroupID, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldContainsFold(FieldModel, v))
}

// SuccessCountEQ applies the EQ predicate on the "success_count" field.
func SuccessCountEQ(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldSuccessCount, v))
}

// SuccessCountNEQ applies the NEQ predicate on the "success_count" field.
func SuccessCountNEQ(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNEQ(FieldSuccessCount, v))
}

// SuccessCountIn applies the In predicate on the "success_count" field.
func SuccessCountIn(vs ...int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldIn(FieldSuccessCount, vs...))
}

// SuccessCountNotIn applies the NotIn predicate on the "success_count" field.
func SuccessCountNotIn(vs ...int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNotIn(FieldSuccessCount, vs...))
}

// SuccessCountGT applies the GT predicate on the "success_count" field.
func SuccessCountGT(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGT(FieldSuccessCount, v))
}

// SuccessCountGTE applies the GTE predicate on the "success_count" field.
func SuccessCountGTE(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGTE(FieldSuccessCount, v))
}

// SuccessCountLT applies the LT predicate on the "success_count" field.
func SuccessCountLT(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLT(FieldSuccessCount, v))
}

// SuccessCountLTE applies the LTE predicate on the "success_count" field.
func SuccessCountLTE(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLTE(FieldSuccessCount, v))
}

// ErrorCountEQ applies the EQ predicate on the "error_count" field.
func ErrorCountEQ(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldErrorCount, v))
}

// ErrorCountNEQ applies the NEQ predicate on the "error_count" field.
func ErrorCountNEQ(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNEQ(FieldErrorCount, v))
}

// ErrorCountIn applies the In predicate on the "error_count" field.
func ErrorCountIn(vs ...int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldIn(FieldErrorCount, vs...))
}

// ErrorCountNotIn applies the NotIn predicate on the "error_count" field.
func ErrorCountNotIn(vs ...int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNotIn(FieldErrorCount, vs...))
}

// ErrorCountGT applies the GT predicate on the "error_count" field.
func ErrorCountGT(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGT(FieldErrorCount, v))
}

// ErrorCountGTE applies the GTE predicate on the "error_count" field.
func ErrorCountGTE(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGTE(FieldErrorCount, v))
}

// ErrorCountLT applies the LT predicate on the "error_count" field.
func ErrorCountLT(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLT(FieldErrorCount, v))
}

// ErrorCountLTE applies the LTE predicate on the "error_count" field.
func ErrorCountLTE(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLTE(FieldErrorCount, v))
}

// RateLimitedCountEQ applies the EQ predicate on the "rate_limited_count" field.
func RateLimitedCountEQ(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldRateLimitedCount, v))
}

// RateLimitedCountNEQ applies the NEQ predicate on the "rate_limited_count" field.
func RateLimitedCountNEQ(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNEQ(FieldRateLimitedCount, v))
}

// RateLimitedCountIn applies the In predicate on the "rate_limited_count" field.
func RateLimitedCountIn(vs ...int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldIn(FieldRateLimitedCount, vs...))
}

// RateLimitedCountNotIn applies the NotIn predicate on the "rate_limited_count" field.
func RateLimitedCountNotIn(vs ...int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNotIn(FieldRateLimitedCount, vs...))
}

// RateLimitedCountGT applies the GT predicate on the "rate_limited_count" field.
func RateLimitedCountGT(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGT(FieldRateLimitedCount, v))
}

// RateLimitedCountGTE applies the GTE predicate on the "rate_limited_count" field.
func RateLimitedCountGTE(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGTE(FieldRateLimitedCount, v))
}

// RateLimitedCountLT applies the LT predicate on the "rate_limited_count" field.
func RateLimitedCountLT(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLT(FieldRateLimitedCount, v))
}

// RateLimitedCountLTE applies the LTE predicate on the "rate_limited_count" field.
func RateLimitedCountLTE(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLTE(FieldRateLimitedCount, v))
}

// OverloadedCountEQ applies the EQ predicate on the "overloaded_count" field.
func OverloadedCountEQ(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldOverloadedCount, v))
}

// OverloadedCountNEQ applies the NEQ predicate on the "overloaded_count" field.
func OverloadedCountNEQ(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNEQ(FieldOverloadedCount, v))
}

// OverloadedCountIn applies the In predicate on the "overloaded_count" field.
func OverloadedCountIn(vs ...int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldIn(FieldOverloadedCount, vs...))
}

// OverloadedCountNotIn applies the NotIn predicate on the "overloaded_count" field.
func OverloadedCountNotIn(vs ...int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNotIn(FieldOverloadedCount, vs...))
}

// OverloadedCountGT applies the GT predicate on the "overloaded_count" field.
func OverloadedCountGT(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGT(FieldOverloadedCount, v))
}

// OverloadedCountGTE applies the GTE predicate on the "overloaded_count" field.
func OverloadedCountGTE(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGTE(FieldOverloadedCount, v))
}

// OverloadedCountLT applies the LT predicate on the "overloaded_count" field.
func OverloadedCountLT(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLT(FieldOverloadedCount, v))
}

// OverloadedCountLTE applies the LTE predicate on the "overloaded_count" field.
func OverloadedCountLTE(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLTE(FieldOverloadedCount, v))
}

// LatencyP50MsEQ applies the EQ predicate on the "latency_p50_ms" field.
func LatencyP50MsEQ(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldLatencyP50Ms, v))
}

// LatencyP50MsNEQ applies the NEQ predicate on the "latency_p50_ms" field.
func LatencyP50MsNEQ(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNEQ(FieldLatencyP50Ms, v))
}

// LatencyP50MsIn applies the In predicate on the "latency_p50_ms" field.
func LatencyP50MsIn(vs ...int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldIn(FieldLatencyP50Ms, vs...))
}

// LatencyP50MsNotIn applies the NotIn predicate on the "latency_p50_ms" field.
func LatencyP50MsNotIn(vs ...int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNotIn(FieldLatencyP50Ms, vs...))
}

// LatencyP50MsGT applies the GT predicate on the "latency_p50_ms" field.
func LatencyP50MsGT(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGT(FieldLatencyP50Ms, v))
}

// LatencyP50MsGTE applies the GTE predicate on the "latency_p50_ms" field.
func LatencyP50MsGTE(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGTE(FieldLatencyP50Ms, v))
}

// LatencyP50MsLT applies the LT predicate on the "latency_p50_ms" field.
func LatencyP50MsLT(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLT(FieldLatencyP50Ms, v))
}

// LatencyP50MsLTE applies the LTE predicate on the "latency_p50_ms" field.
func LatencyP50MsLTE(v int) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLTE(FieldLatencyP50Ms, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldContainsFold(FieldSource, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChannelHealthSample) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChannelHealthSample) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChannelHealthSample) predicate.ChannelHealthSample {
	return predicate.ChannelHealthSample(sql.NotPredicates(p))
}
