// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/channelhealthsample"
)

// ChannelHealthSample is the model entity for the ChannelHealthSample schema.
type ChannelHealthSample struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 采样所属 1 分钟桶起点 (UTC)
	BucketTs time.Time `json:"bucket_ts,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// 分组 id;0 表示无分组(原生 anthropic 路由)
	GroupID int64 `json:"group_id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// SuccessCount holds the value of the "success_count" field.
	SuccessCount int `json:"success_count,omitempty"`
	// ErrorCount holds the value of the "error_count" field.
	ErrorCount int `json:"error_count,omitempty"`
	// 429 计数
	RateLimitedCount int `json:"rate_limited_count,omitempty"`
	// 529 计数
	OverloadedCount int `json:"overloaded_count,omitempty"`
	// LatencyP50Ms holds the value of the "latency_p50_ms" field.
	LatencyP50Ms int `json:"latency_p50_ms,omitempty"`
	// 采样来源: "passive" | "active_probe"
	Source string `json:"source,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelHealthSample) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelhealthsample.FieldID, channelhealthsample.FieldAccountID, channelhealthsample.FieldGroupID, channelhealthsample.FieldSuccessCount, channelhealthsample.FieldErrorCount, channelhealthsample.FieldRateLimitedCount, channelhealthsample.FieldOverloadedCount, channelhealthsample.FieldLatencyP50Ms:
			values[i] = new(sql.NullInt64)
		case channelhealthsample.FieldModel, channelhealthsample.FieldSource:
			values[i] = new(sql.NullString)
		case channelhealthsample.FieldBucketTs, channelhealthsample.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelHealthSample fields.
func (_m *ChannelHealthSample) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelhealthsample.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case channelhealthsample.FieldBucketTs:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field bucket_ts", values[i])
			} else if value.Valid {
				_m.BucketTs = value.Time
			}
		case channelhealthsample.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case channelhealthsample.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case channelhealthsample.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case channelhealthsample.FieldSuccessCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field success_count", values[i])
			} else if value.Valid {
				_m.SuccessCount = int(value.Int64)
			}
		case channelhealthsample.FieldErrorCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field error_count", values[i])
			} else if value.Valid {
				_m.ErrorCount = int(value.Int64)
			}
		case channelhealthsample.FieldRateLimitedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_limited_count", values[i])
			} else if value.Valid {
				_m.RateLimitedCount = int(value.Int64)
			}
		case channelhealthsample.FieldOverloadedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field overloaded_count", values[i])
			} else if value.Valid {
				_m.OverloadedCount = int(value.Int64)
			}
		case channelhealthsample.FieldLatencyP50Ms:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field latency_p50_ms", values[i])
			} else if value.Valid {
				_m.LatencyP50Ms = int(value.Int64)
			}
		case channelhealthsample.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case channelhealthsample.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelHealthSample.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelHealthSample) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ChannelHealthSample.
// Note that you need to call ChannelHealthSample.Unwrap() before calling this method if this ChannelHealthSample
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelHealthSample) Update() *ChannelHealthSampleUpdateOne {
	return NewChannelHealthSampleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelHealthSample entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelHealthSample) Unwrap() *ChannelHealthSample {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelHealthSample is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelHealthSample) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelHealthSample(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("bucket_ts=")
	builder.WriteString(_m.BucketTs.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("success_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuccessCount))
	builder.WriteString(", ")
	builder.WriteString("error_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorCount))
	builder.WriteString(", ")
	builder.WriteString("rate_limited_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateLimitedCount))
	builder.WriteString(", ")
	builder.WriteString("overloaded_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.OverloadedCount))
	builder.WriteString(", ")
	builder.WriteString("latency_p50_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.LatencyP50Ms))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelHealthSamples is a parsable slice of ChannelHealthSample.
type ChannelHealthSamples []*ChannelHealthSample
