// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelhealthsample"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChannelHealthSampleUpdate is the builder for updating ChannelHealthSample entities.
type ChannelHealthSampleUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelHealthSampleMutation
}

// Where appends a list predicates to the ChannelHealthSampleUpdate builder.
func (_u *ChannelHealthSampleUpdate) Where(ps ...predicate.ChannelHealthSample) *ChannelHealthSampleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBucketTs sets the "bucket_ts" field.
func (_u *ChannelHealthSampleUpdate) SetBucketTs(v time.Time) *ChannelHealthSampleUpdate {
	_u.mutation.SetBucketTs(v)
	return _u
}

// SetNillableBucketTs sets the "bucket_ts" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdate) SetNillableBucketTs(v *time.Time) *ChannelHealthSampleUpdate {
	if v != nil {
		_u.SetBucketTs(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ChannelHealthSampleUpdate) SetAccountID(v int64) *ChannelHealthSampleUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdate) SetNillableAccountID(v *int64) *ChannelHealthSampleUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *ChannelHealthSampleUpdate) AddAccountID(v int64) *ChannelHealthSampleUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ChannelHealthSampleUpdate) SetGroupID(v int64) *ChannelHealthSampleUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdate) SetNillableGroupID(v *int64) *ChannelHealthSampleUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *ChannelHealthSampleUpdate) AddGroupID(v int64) *ChannelHealthSampleUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *ChannelHealthSampleUpdate) SetModel(v string) *ChannelHealthSampleUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdate) SetNillableModel(v *string) *ChannelHealthSampleUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetSuccessCount sets the "success_count" field.
func (_u *ChannelHealthSampleUpdate) SetSuccessCount(v int) *ChannelHealthSampleUpdate {
	_u.mutation.ResetSuccessCount()
	_u.mutation.SetSuccessCount(v)
	return _u
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdate) SetNillableSuccessCount(v *int) *ChannelHealthSampleUpdate {
	if v != nil {
		_u.SetSuccessCount(*v)
	}
	return _u
}

// AddSuccessCount adds value to the "success_count" field.
func (_u *ChannelHealthSampleUpdate) AddSuccessCount(v int) *ChannelHealthSampleUpdate {
	_u.mutation.AddSuccessCount(v)
	return _u
}

// SetErrorCount sets the "error_count" field.
func (_u *ChannelHealthSampleUpdate) SetErrorCount(v int) *ChannelHealthSampleUpdate {
	_u.mutation.ResetErrorCount()
	_u.mutation.SetErrorCount(v)
	return _u
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdate) SetNillableErrorCount(v *int) *ChannelHealthSampleUpdate {
	if v != nil {
		_u.SetErrorCount(*v)
	}
	return _u
}

// AddErrorCount adds value to the "error_count" field.
func (_u *ChannelHealthSampleUpdate) AddErrorCount(v int) *ChannelHealthSampleUpdate {
	_u.mutation.AddErrorCount(v)
	return _u
}

// SetRateLimitedCount sets the "rate_limited_count" field.
func (_u *ChannelHealthSampleUpdate) SetRateLimitedCount(v int) *ChannelHealthSampleUpdate {
	_u.mutation.ResetRateLimitedCount()
	_u.mutation.SetRateLimitedCount(v)
	return _u
}

// SetNillableRateLimitedCount sets the "rate_limited_count" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdate) SetNillableRateLimitedCount(v *int) *ChannelHealthSampleUpdate {
	if v != nil {
		_u.SetRateLimitedCount(*v)
	}
	return _u
}

// AddRateLimitedCount adds value to the "rate_limited_count" field.
func (_u *ChannelHealthSampleUpdate) AddRateLimitedCount(v int) *ChannelHealthSampleUpdate {
	_u.mutation.AddRateLimitedCount(v)
	return _u
}

// SetOverloadedCount sets the "overloaded_count" field.
func (_u *ChannelHealthSampleUpdate) SetOverloadedCount(v int) *ChannelHealthSampleUpdate {
	_u.mutation.ResetOverloadedCount()
	_u.mutation.SetOverloadedCount(v)
	return _u
}

// SetNillableOverloadedCount sets the "overloaded_count" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdate) SetNillableOverloadedCount(v *int) *ChannelHealthSampleUpdate {
	if v != nil {
		_u.SetOverloadedCount(*v)
	}
	return _u
}

// AddOverloadedCount adds value to the "overloaded_count" field.
func (_u *ChannelHealthSampleUpdate) AddOverloadedCount(v int) *ChannelHealthSampleUpdate {
	_u.mutation.AddOverloadedCount(v)
	return _u
}

// SetLatencyP50Ms sets the "latency_p50_ms" field.
func (_u *ChannelHealthSampleUpdate) SetLatencyP50Ms(v int) *ChannelHealthSampleUpdate {
	_u.mutation.ResetLatencyP50Ms()
	_u.mutation.SetLatencyP50Ms(v)
	return _u
}

// SetNillableLatencyP50Ms sets the "latency_p50_ms" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdate) SetNillableLatencyP50Ms(v *int) *ChannelHealthSampleUpdate {
	if v != nil {
		_u.SetLatencyP50Ms(*v)
	}
	return _u
}

// AddLatencyP50Ms adds value to the "latency_p50_ms" field.
func (_u *ChannelHealthSampleUpdate) AddLatencyP50Ms(v int) *ChannelHealthSampleUpdate {
	_u.mutation.AddLatencyP50Ms(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *ChannelHealthSampleUpdate) SetSource(v string) *ChannelHealthSampleUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdate) SetNillableSource(v *string) *ChannelHealthSampleUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// Mutation returns the ChannelHealthSampleMutation object of the builder.
func (_u *ChannelHealthSampleUpdate) Mutation() *ChannelHealthSampleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelHealthSampleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelHealthSampleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelHealthSampleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelHealthSampleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelHealthSampleUpdate) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := channelhealthsample.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ChannelHealthSample.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := channelhealthsample.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ChannelHealthSample.source": %w`, err)}
		}
	}
	return nil
}

func (_u *ChannelHealthSampleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelhealthsample.Table, channelhealthsample.Columns, sqlgraph.NewFieldSpec(channelhealthsample.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BucketTs(); ok {
		_spec.SetField(channelhealthsample.FieldBucketTs, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(channelhealthsample.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(channelhealthsample.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(channelhealthsample.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(channelhealthsample.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(channelhealthsample.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SuccessCount(); ok {
		_spec.SetField(channelhealthsample.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuccessCount(); ok {
		_spec.AddField(channelhealthsample.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorCount(); ok {
		_spec.SetField(channelhealthsample.FieldErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedErrorCount(); ok {
		_spec.AddField(channelhealthsample.FieldErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RateLimitedCount(); ok {
		_spec.SetField(channelhealthsample.FieldRateLimitedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRateLimitedCount(); ok {
		_spec.AddField(channelhealthsample.FieldRateLimitedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OverloadedCount(); ok {
		_spec.SetField(channelhealthsample.FieldOverloadedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOverloadedCount(); ok {
		_spec.AddField(channelhealthsample.FieldOverloadedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyP50Ms(); ok {
		_spec.SetField(channelhealthsample.FieldLatencyP50Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyP50Ms(); ok {
		_spec.AddField(channelhealthsample.FieldLatencyP50Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(channelhealthsample.FieldSource, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelhealthsample.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelHealthSampleUpdateOne is the builder for updating a single ChannelHealthSample entity.
type ChannelHealthSampleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelHealthSampleMutation
}

// SetBucketTs sets the "bucket_ts" field.
func (_u *ChannelHealthSampleUpdateOne) SetBucketTs(v time.Time) *ChannelHealthSampleUpdateOne {
	_u.mutation.SetBucketTs(v)
	return _u
}

// SetNillableBucketTs sets the "bucket_ts" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdateOne) SetNillableBucketTs(v *time.Time) *ChannelHealthSampleUpdateOne {
	if v != nil {
		_u.SetBucketTs(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ChannelHealthSampleUpdateOne) SetAccountID(v int64) *ChannelHealthSampleUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdateOne) SetNillableAccountID(v *int64) *ChannelHealthSampleUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *ChannelHealthSampleUpdateOne) AddAccountID(v int64) *ChannelHealthSampleUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ChannelHealthSampleUpdateOne) SetGroupID(v int64) *ChannelHealthSampleUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdateOne) SetNillableGroupID(v *int64) *ChannelHealthSampleUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *ChannelHealthSampleUpdateOne) AddGroupID(v int64) *ChannelHealthSampleUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *ChannelHealthSampleUpdateOne) SetModel(v string) *ChannelHealthSampleUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdateOne) SetNillableModel(v *string) *ChannelHealthSampleUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetSuccessCount sets the "success_count" field.
func (_u *ChannelHealthSampleUpdateOne) SetSuccessCount(v int) *ChannelHealthSampleUpdateOne {
	_u.mutation.ResetSuccessCount()
	_u.mutation.SetSuccessCount(v)
	return _u
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdateOne) SetNillableSuccessCount(v *int) *ChannelHealthSampleUpdateOne {
	if v != nil {
		_u.SetSuccessCount(*v)
	}
	return _u
}

// AddSuccessCount adds value to the "success_count" field.
func (_u *ChannelHealthSampleUpdateOne) AddSuccessCount(v int) *ChannelHealthSampleUpdateOne {
	_u.mutation.AddSuccessCount(v)
	return _u
}

// SetErrorCount sets the "error_count" field.
func (_u *ChannelHealthSampleUpdateOne) SetErrorCount(v int) *ChannelHealthSampleUpdateOne {
	_u.mutation.ResetErrorCount()
	_u.mutation.SetErrorCount(v)
	return _u
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdateOne) SetNillableErrorCount(v *int) *ChannelHealthSampleUpdateOne {
	if v != nil {
		_u.SetErrorCount(*v)
	}
	return _u
}

// AddErrorCount adds value to the "error_count" field.
func (_u *ChannelHealthSampleUpdateOne) AddErrorCount(v int) *ChannelHealthSampleUpdateOne {
	_u.mutation.AddErrorCount(v)
	return _u
}

// SetRateLimitedCount sets the "rate_limited_count" field.
func (_u *ChannelHealthSampleUpdateOne) SetRateLimitedCount(v int) *ChannelHealthSampleUpdateOne {
	_u.mutation.ResetRateLimitedCount()
	_u.mutation.SetRateLimitedCount(v)
	return _u
}

// SetNillableRateLimitedCount sets the "rate_limited_count" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdateOne) SetNillableRateLimitedCount(v *int) *ChannelHealthSampleUpdateOne {
	if v != nil {
		_u.SetRateLimitedCount(*v)
	}
	return _u
}

// AddRateLimitedCount adds value to the "rate_limited_count" field.
func (_u *ChannelHealthSampleUpdateOne) AddRateLimitedCount(v int) *ChannelHealthSampleUpdateOne {
	_u.mutation.AddRateLimitedCount(v)
	return _u
}

// SetOverloadedCount sets the "overloaded_count" field.
func (_u *ChannelHealthSampleUpdateOne) SetOverloadedCount(v int) *ChannelHealthSampleUpdateOne {
	_u.mutation.ResetOverloadedCount()
	_u.mutation.SetOverloadedCount(v)
	return _u
}

// SetNillableOverloadedCount sets the "overloaded_count" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdateOne) SetNillableOverloadedCount(v *int) *ChannelHealthSampleUpdateOne {
	if v != nil {
		_u.SetOverloadedCount(*v)
	}
	return _u
}

// AddOverloadedCount adds value to the "overloaded_count" field.
func (_u *ChannelHealthSampleUpdateOne) AddOverloadedCount(v int) *ChannelHealthSampleUpdateOne {
	_u.mutation.AddOverloadedCount(v)
	return _u
}

// SetLatencyP50Ms sets the "latency_p50_ms" field.
func (_u *ChannelHealthSampleUpdateOne) SetLatencyP50Ms(v int) *ChannelHealthSampleUpdateOne {
	_u.mutation.ResetLatencyP50Ms()
	_u.mutation.SetLatencyP50Ms(v)
	return _u
}

// SetNillableLatencyP50Ms sets the "latency_p50_ms" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdateOne) SetNillableLatencyP50Ms(v *int) *ChannelHealthSampleUpdateOne {
	if v != nil {
		_u.SetLatencyP50Ms(*v)
	}
	return _u
}

// AddLatencyP50Ms adds value to the "latency_p50_ms" field.
func (_u *ChannelHealthSampleUpdateOne) AddLatencyP50Ms(v int) *ChannelHealthSampleUpdateOne {
	_u.mutation.AddLatencyP50Ms(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *ChannelHealthSampleUpdateOne) SetSource(v string) *ChannelHealthSampleUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ChannelHealthSampleUpdateOne) SetNillableSource(v *string) *ChannelHealthSampleUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// Mutation returns the ChannelHealthSampleMutation object of the builder.
func (_u *ChannelHealthSampleUpdateOne) Mutation() *ChannelHealthSampleMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChannelHealthSampleUpdate builder.
func (_u *ChannelHealthSampleUpdateOne) Where(ps ...predicate.ChannelHealthSample) *ChannelHealthSampleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelHealthSampleUpdateOne) Select(field string, fields ...string) *ChannelHealthSampleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelHealthSample entity.
func (_u *ChannelHealthSampleUpdateOne) Save(ctx context.Context) (*ChannelHealthSample, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelHealthSampleUpdateOne) SaveX(ctx context.Context) *ChannelHealthSample {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelHealthSampleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelHealthSampleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelHealthSampleUpdateOne) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := channelhealthsample.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ChannelHealthSample.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := channelhealthsample.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ChannelHealthSample.source": %w`, err)}
		}
	}
	return nil
}

func (_u *ChannelHealthSampleUpdateOne) sqlSave(ctx context.Context) (_node *ChannelHealthSample, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelhealthsample.Table, channelhealthsample.Columns, sqlgraph.NewFieldSpec(channelhealthsample.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelHealthSample.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelhealthsample.FieldID)
		for _, f := range fields {
			if !channelhealthsample.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelhealthsample.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BucketTs(); ok {
		_spec.SetField(channelhealthsample.FieldBucketTs, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(channelhealthsample.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(channelhealthsample.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(channelhealthsample.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(channelhealthsample.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(channelhealthsample.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SuccessCount(); ok {
		_spec.SetField(channelhealthsample.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuccessCount(); ok {
		_spec.AddField(channelhealthsample.FieldSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorCount(); ok {
		_spec.SetField(channelhealthsample.FieldErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedErrorCount(); ok {
		_spec.AddField(channelhealthsample.FieldErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RateLimitedCount(); ok {
		_spec.SetField(channelhealthsample.FieldRateLimitedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRateLimitedCount(); ok {
		_spec.AddField(channelhealthsample.FieldRateLimitedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OverloadedCount(); ok {
		_spec.SetField(channelhealthsample.FieldOverloadedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOverloadedCount(); ok {
		_spec.AddField(channelhealthsample.FieldOverloadedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyP50Ms(); ok {
		_spec.SetField(channelhealthsample.FieldLatencyP50Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyP50Ms(); ok {
		_spec.AddField(channelhealthsample.FieldLatencyP50Ms, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(channelhealthsample.FieldSource, field.TypeString, value)
	}
	_node = &ChannelHealthSample{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelhealthsample.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
