// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelhealthsample"
)

// ChannelHealthSampleCreate is the builder for creating a ChannelHealthSample entity.
type ChannelHealthSampleCreate struct {
	config
	mutation *ChannelHealthSampleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBucketTs sets the "bucket_ts" field.
func (_c *ChannelHealthSampleCreate) SetBucketTs(v time.Time) *ChannelHealthSampleCreate {
	_c.mutation.SetBucketTs(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ChannelHealthSampleCreate) SetAccountID(v int64) *ChannelHealthSampleCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ChannelHealthSampleCreate) SetGroupID(v int64) *ChannelHealthSampleCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *ChannelHealthSampleCreate) SetModel(v string) *ChannelHealthSampleCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetSuccessCount sets the "success_count" field.
func (_c *ChannelHealthSampleCreate) SetSuccessCount(v int) *ChannelHealthSampleCreate {
	_c.mutation.SetSuccessCount(v)
	return _c
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_c *ChannelHealthSampleCreate) SetNillableSuccessCount(v *int) *ChannelHealthSampleCreate {
	if v != nil {
		_c.SetSuccessCount(*v)
	}
	return _c
}

// SetErrorCount sets the "error_count" field.
func (_c *ChannelHealthSampleCreate) SetErrorCount(v int) *ChannelHealthSampleCreate {
	_c.mutation.SetErrorCount(v)
	return _c
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_c *ChannelHealthSampleCreate) SetNillableErrorCount(v *int) *ChannelHealthSampleCreate {
	if v != nil {
		_c.SetErrorCount(*v)
	}
	return _c
}

// SetRateLimitedCount sets the "rate_limited_count" field.
func (_c *ChannelHealthSampleCreate) SetRateLimitedCount(v int) *ChannelHealthSampleCreate {
	_c.mutation.SetRateLimitedCount(v)
	return _c
}

// SetNillableRateLimitedCount sets the "rate_limited_count" field if the given value is not nil.
func (_c *ChannelHealthSampleCreate) SetNillableRateLimitedCount(v *int) *ChannelHealthSampleCreate {
	if v != nil {
		_c.SetRateLimitedCount(*v)
	}
	return _c
}

// SetOverloadedCount sets the "overloaded_count" field.
func (_c *ChannelHealthSampleCreate) SetOverloadedCount(v int) *ChannelHealthSampleCreate {
	_c.mutation.SetOverloadedCount(v)
	return _c
}

// SetNillableOverloadedCount sets the "overloaded_count" field if the given value is not nil.
func (_c *ChannelHealthSampleCreate) SetNillableOverloadedCount(v *int) *ChannelHealthSampleCreate {
	if v != nil {
		_c.SetOverloadedCount(*v)
	}
	return _c
}

// SetLatencyP50Ms sets the "latency_p50_ms" field.
func (_c *ChannelHealthSampleCreate) SetLatencyP50Ms(v int) *ChannelHealthSampleCreate {
	_c.mutation.SetLatencyP50Ms(v)
	return _c
}

// SetNillableLatencyP50Ms sets the "latency_p50_ms" field if the given value is not nil.
func (_c *ChannelHealthSampleCreate) SetNillableLatencyP50Ms(v *int) *ChannelHealthSampleCreate {
	if v != nil {
		_c.SetLatencyP50Ms(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *ChannelHealthSampleCreate) SetSource(v string) *ChannelHealthSampleCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *ChannelHealthSampleCreate) SetNillableSource(v *string) *ChannelHealthSampleCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelHealthSampleCreate) SetCreatedAt(v time.Time) *ChannelHealthSampleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelHealthSampleCreate) SetNillableCreatedAt(v *time.Time) *ChannelHealthSampleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChannelHealthSampleCreate) SetID(v int64) *ChannelHealthSampleCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ChannelHealthSampleMutation object of the builder.
func (_c *ChannelHealthSampleCreate) Mutation() *ChannelHealthSampleMutation {
	return _c.mutation
}

// Save creates the ChannelHealthSample in the database.
func (_c *ChannelHealthSampleCreate) Save(ctx context.Context) (*ChannelHealthSample, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelHealthSampleCreate) SaveX(ctx context.Context) *ChannelHealthSample {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelHealthSampleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelHealthSampleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelHealthSampleCreate) defaults() {
	if _, ok := _c.mutation.SuccessCount(); !ok {
		v := channelhealthsample.DefaultSuccessCount
		_c.mutation.SetSuccessCount(v)
	}
	if _, ok := _c.mutation.ErrorCount(); !ok {
		v := channelhealthsample.DefaultErrorCount
		_c.mutation.SetErrorCount(v)
	}
	if _, ok := _c.mutation.RateLimitedCount(); !ok {
		v := channelhealthsample.DefaultRateLimitedCount
		_c.mutation.SetRateLimitedCount(v)
	}
	if _, ok := _c.mutation.OverloadedCount(); !ok {
		v := channelhealthsample.DefaultOverloadedCount
		_c.mutation.SetOverloadedCount(v)
	}
	if _, ok := _c.mutation.LatencyP50Ms(); !ok {
		v := channelhealthsample.DefaultLatencyP50Ms
		_c.mutation.SetLatencyP50Ms(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := channelhealthsample.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := channelhealthsample.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelHealthSampleCreate) check() error {
	if _, ok := _c.mutation.BucketTs(); !ok {
		return &ValidationError{Name: "bucket_ts", err: errors.New(`ent: missing required field "ChannelHealthSample.bucket_ts"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ChannelHealthSample.account_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "ChannelHealthSample.group_id"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "ChannelHealthSample.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := channelhealthsample.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ChannelHealthSample.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SuccessCount(); !ok {
		return &ValidationError{Name: "success_count", err: errors.New(`ent: missing required field "ChannelHealthSample.success_count"`)}
	}
	if _, ok := _c.mutation.ErrorCount(); !ok {
		return &ValidationError{Name: "error_count", err: errors.New(`ent: missing required field "ChannelHealthSample.error_count"`)}
	}
	if _, ok := _c.mutation.RateLimitedCount(); !ok {
		return &ValidationError{Name: "rate_limited_count", err: errors.New(`ent: missing required field "ChannelHealthSample.rate_limited_count"`)}
	}
	if _, ok := _c.mutation.OverloadedCount(); !ok {
		return &ValidationError{Name: "overloaded_count", err: errors.New(`ent: missing required field "ChannelHealthSample.overloaded_count"`)}
	}
	if _, ok := _c.mutation.LatencyP50Ms(); !ok {
		return &ValidationError{Name: "latency_p50_ms", err: errors.New(`ent: missing required field "ChannelHealthSample.latency_p50_ms"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "ChannelHealthSample.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := channelhealthsample.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ChannelHealthSample.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChannelHealthSample.created_at"`)}
	}
	return nil
}

func (_c *ChannelHealthSampleCreate) sqlSave(ctx context.Context) (*ChannelHealthSample, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelHealthSampleCreate) createSpec() (*ChannelHealthSample, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelHealthSample{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelhealthsample.Table, sqlgraph.NewFieldSpec(channelhealthsample.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.BucketTs(); ok {
		_spec.SetField(channelhealthsample.FieldBucketTs, field.TypeTime, value)
		_node.BucketTs = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(channelhealthsample.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(channelhealthsample.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(channelhealthsample.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.SuccessCount(); ok {
		_spec.SetField(channelhealthsample.FieldSuccessCount, field.TypeInt, value)
		_node.SuccessCount = value
	}
	if value, ok := _c.mutation.ErrorCount(); ok {
		_spec.SetField(channelhealthsample.FieldErrorCount, field.TypeInt, value)
		_node.ErrorCount = value
	}
	if value, ok := _c.mutation.RateLimitedCount(); ok {
		_spec.SetField(channelhealthsample.FieldRateLimitedCount, field.TypeInt, value)
		_node.RateLimitedCount = value
	}
	if value, ok := _c.mutation.OverloadedCount(); ok {
		_spec.SetField(channelhealthsample.FieldOverloadedCount, field.TypeInt, value)
		_node.OverloadedCount = value
	}
	if value, ok := _c.mutation.LatencyP50Ms(); ok {
		_spec.SetField(channelhealthsample.FieldLatencyP50Ms, field.TypeInt, value)
		_node.LatencyP50Ms = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(channelhealthsample.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channelhealthsample.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelHealthSample.Create().
//		SetBucketTs(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelHealthSampleUpsert) {
//			SetBucketTs(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelHealthSampleCreate) OnConflict(opts ...sql.ConflictOption) *ChannelHealthSampleUpsertOne {
	_c.conflict = opts
	return &ChannelHealthSampleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelHealthSample.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelHealthSampleCreate) OnConflictColumns(columns ...string) *ChannelHealthSampleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelHealthSampleUpsertOne{
		create: _c,
	}
}

type (
	// ChannelHealthSampleUpsertOne is the builder for "upsert"-ing
	//  one ChannelHealthSample node.
	ChannelHealthSampleUpsertOne struct {
		create *ChannelHealthSampleCreate
	}

	// ChannelHealthSampleUpsert is the "OnConflict" setter.
	ChannelHealthSampleUpsert struct {
		*sql.UpdateSet
	}
)

// SetBucketTs sets the "bucket_ts" field.
func (u *ChannelHealthSampleUpsert) SetBucketTs(v time.Time) *ChannelHealthSampleUpsert {
	u.Set(channelhealthsample.FieldBucketTs, v)
	return u
}

// UpdateBucketTs sets the "bucket_ts" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsert) UpdateBucketTs() *ChannelHealthSampleUpsert {
	u.SetExcluded(channelhealthsample.FieldBucketTs)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *ChannelHealthSampleUpsert) SetAccountID(v int64) *ChannelHealthSampleUpsert {
	u.Set(channelhealthsample.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsert) UpdateAccountID() *ChannelHealthSampleUpsert {
	u.SetExcluded(channelhealthsample.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *ChannelHealthSampleUpsert) AddAccountID(v int64) *ChannelHealthSampleUpsert {
	u.Add(channelhealthsample.FieldAccountID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *ChannelHealthSampleUpsert) SetGroupID(v int64) *ChannelHealthSampleUpsert {
	u.Set(channelhealthsample.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsert) UpdateGroupID() *ChannelHealthSampleUpsert {
	u.SetExcluded(channelhealthsample.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *ChannelHealthSampleUpsert) AddGroupID(v int64) *ChannelHealthSampleUpsert {
	u.Add(channelhealthsample.FieldGroupID, v)
	return u
}

// SetModel sets the "model" field.
func (u *ChannelHealthSampleUpsert) SetModel(v string) *ChannelHealthSampleUpsert {
	u.Set(channelhealthsample.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsert) UpdateModel() *ChannelHealthSampleUpsert {
	u.SetExcluded(channelhealthsample.FieldModel)
	return u
}

// SetSuccessCount sets the "success_count" field.
func (u *ChannelHealthSampleUpsert) SetSuccessCount(v int) *ChannelHealthSampleUpsert {
	u.Set(channelhealthsample.FieldSuccessCount, v)
	return u
}

// UpdateSuccessCount sets the "success_count" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsert) UpdateSuccessCount() *ChannelHealthSampleUpsert {
	u.SetExcluded(channelhealthsample.FieldSuccessCount)
	return u
}

// AddSuccessCount adds v to the "success_count" field.
func (u *ChannelHealthSampleUpsert) AddSuccessCount(v int) *ChannelHealthSampleUpsert {
	u.Add(channelhealthsample.FieldSuccessCount, v)
	return u
}

// SetErrorCount sets the "error_count" field.
func (u *ChannelHealthSampleUpsert) SetErrorCount(v int) *ChannelHealthSampleUpsert {
	u.Set(channelhealthsample.FieldErrorCount, v)
	return u
}

// UpdateErrorCount sets the "error_count" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsert) UpdateErrorCount() *ChannelHealthSampleUpsert {
	u.SetExcluded(channelhealthsample.FieldErrorCount)
	return u
}

// AddErrorCount adds v to the "error_count" field.
func (u *ChannelHealthSampleUpsert) AddErrorCount(v int) *ChannelHealthSampleUpsert {
	u.Add(channelhealthsample.FieldErrorCount, v)
	return u
}

// SetRateLimitedCount sets the "rate_limited_count" field.
func (u *ChannelHealthSampleUpsert) SetRateLimitedCount(v int) *ChannelHealthSampleUpsert {
	u.Set(channelhealthsample.FieldRateLimitedCount, v)
	return u
}

// UpdateRateLimitedCount sets the "rate_limited_count" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsert) UpdateRateLimitedCount() *ChannelHealthSampleUpsert {
	u.SetExcluded(channelhealthsample.FieldRateLimitedCount)
	return u
}

// AddRateLimitedCount adds v to the "rate_limited_count" field.
func (u *ChannelHealthSampleUpsert) AddRateLimitedCount(v int) *ChannelHealthSampleUpsert {
	u.Add(channelhealthsample.FieldRateLimitedCount, v)
	return u
}

// SetOverloadedCount sets the "overloaded_count" field.
func (u *ChannelHealthSampleUpsert) SetOverloadedCount(v int) *ChannelHealthSampleUpsert {
	u.Set(channelhealthsample.FieldOverloadedCount, v)
	return u
}

// UpdateOverloadedCount sets the "overloaded_count" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsert) UpdateOverloadedCount() *ChannelHealthSampleUpsert {
	u.SetExcluded(channelhealthsample.FieldOverloadedCount)
	return u
}

// AddOverloadedCount adds v to the "overloaded_count" field.
func (u *ChannelHealthSampleUpsert) AddOverloadedCount(v int) *ChannelHealthSampleUpsert {
	u.Add(channelhealthsample.FieldOverloadedCount, v)
	return u
}

// SetLatencyP50Ms sets the "latency_p50_ms" field.
func (u *ChannelHealthSampleUpsert) SetLatencyP50Ms(v int) *ChannelHealthSampleUpsert {
	u.Set(channelhealthsample.FieldLatencyP50Ms, v)
	return u
}

// UpdateLatencyP50Ms sets the "latency_p50_ms" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsert) UpdateLatencyP50Ms() *ChannelHealthSampleUpsert {
	u.SetExcluded(channelhealthsample.FieldLatencyP50Ms)
	return u
}

// AddLatencyP50Ms adds v to the "latency_p50_ms" field.
func (u *ChannelHealthSampleUpsert) AddLatencyP50Ms(v int) *ChannelHealthSampleUpsert {
	u.Add(channelhealthsample.FieldLatencyP50Ms, v)
	return u
}

// SetSource sets the "source" field.
func (u *ChannelHealthSampleUpsert) SetSource(v string) *ChannelHealthSampleUpsert {
	u.Set(channelhealthsample.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsert) UpdateSource() *ChannelHealthSampleUpsert {
	u.SetExcluded(channelhealthsample.FieldSource)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ChannelHealthSample.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(channelhealthsample.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChannelHealthSampleUpsertOne) UpdateNewValues() *ChannelHealthSampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(channelhealthsample.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(channelhealthsample.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelHealthSample.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChannelHealthSampleUpsertOne) Ignore() *ChannelHealthSampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelHealthSampleUpsertOne) DoNothing() *ChannelHealthSampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelHealthSampleCreate.OnConflict
// documentation for more info.
func (u *ChannelHealthSampleUpsertOne) Update(set func(*ChannelHealthSampleUpsert)) *ChannelHealthSampleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelHealthSampleUpsert{UpdateSet: update})
	}))
	return u
}

// SetBucketTs sets the "bucket_ts" field.
func (u *ChannelHealthSampleUpsertOne) SetBucketTs(v time.Time) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetBucketTs(v)
	})
}

// UpdateBucketTs sets the "bucket_ts" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertOne) UpdateBucketTs() *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateBucketTs()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ChannelHealthSampleUpsertOne) SetAccountID(v int64) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *ChannelHealthSampleUpsertOne) AddAccountID(v int64) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertOne) UpdateAccountID() *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ChannelHealthSampleUpsertOne) SetGroupID(v int64) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *ChannelHealthSampleUpsertOne) AddGroupID(v int64) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertOne) UpdateGroupID() *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateGroupID()
	})
}

// SetModel sets the "model" field.
func (u *ChannelHealthSampleUpsertOne) SetModel(v string) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertOne) UpdateModel() *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateModel()
	})
}

// SetSuccessCount sets the "success_count" field.
func (u *ChannelHealthSampleUpsertOne) SetSuccessCount(v int) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetSuccessCount(v)
	})
}

// AddSuccessCount adds v to the "success_count" field.
func (u *ChannelHealthSampleUpsertOne) AddSuccessCount(v int) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.AddSuccessCount(v)
	})
}

// UpdateSuccessCount sets the "success_count" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertOne) UpdateSuccessCount() *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateSuccessCount()
	})
}

// SetErrorCount sets the "error_count" field.
func (u *ChannelHealthSampleUpsertOne) SetErrorCount(v int) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetErrorCount(v)
	})
}

// AddErrorCount adds v to the "error_count" field.
func (u *ChannelHealthSampleUpsertOne) AddErrorCount(v int) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.AddErrorCount(v)
	})
}

// UpdateErrorCount sets the "error_count" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertOne) UpdateErrorCount() *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateErrorCount()
	})
}

// SetRateLimitedCount sets the "rate_limited_count" field.
func (u *ChannelHealthSampleUpsertOne) SetRateLimitedCount(v int) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetRateLimitedCount(v)
	})
}

// AddRateLimitedCount adds v to the "rate_limited_count" field.
func (u *ChannelHealthSampleUpsertOne) AddRateLimitedCount(v int) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.AddRateLimitedCount(v)
	})
}

// UpdateRateLimitedCount sets the "rate_limited_count" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertOne) UpdateRateLimitedCount() *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateRateLimitedCount()
	})
}

// SetOverloadedCount sets the "overloaded_count" field.
func (u *ChannelHealthSampleUpsertOne) SetOverloadedCount(v int) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetOverloadedCount(v)
	})
}

// AddOverloadedCount adds v to the "overloaded_count" field.
func (u *ChannelHealthSampleUpsertOne) AddOverloadedCount(v int) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.AddOverloadedCount(v)
	})
}

// UpdateOverloadedCount sets the "overloaded_count" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertOne) UpdateOverloadedCount() *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateOverloadedCount()
	})
}

// SetLatencyP50Ms sets the "latency_p50_ms" field.
func (u *ChannelHealthSampleUpsertOne) SetLatencyP50Ms(v int) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetLatencyP50Ms(v)
	})
}

// AddLatencyP50Ms adds v to the "latency_p50_ms" field.
func (u *ChannelHealthSampleUpsertOne) AddLatencyP50Ms(v int) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.AddLatencyP50Ms(v)
	})
}

// UpdateLatencyP50Ms sets the "latency_p50_ms" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertOne) UpdateLatencyP50Ms() *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateLatencyP50Ms()
	})
}

// SetSource sets the "source" field.
func (u *ChannelHealthSampleUpsertOne) SetSource(v string) *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertOne) UpdateSource() *ChannelHealthSampleUpsertOne {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateSource()
	})
}

// Exec executes the query.
func (u *ChannelHealthSampleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelHealthSampleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelHealthSampleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChannelHealthSampleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChannelHealthSampleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChannelHealthSampleCreateBulk is the builder for creating many ChannelHealthSample entities in bulk.
type ChannelHealthSampleCreateBulk struct {
	config
	err      error
	builders []*ChannelHealthSampleCreate
	conflict []sql.ConflictOption
}

// Save creates the ChannelHealthSample entities in the database.
func (_c *ChannelHealthSampleCreateBulk) Save(ctx context.Context) ([]*ChannelHealthSample, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelHealthSample, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelHealthSampleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelHealthSampleCreateBulk) SaveX(ctx context.Context) []*ChannelHealthSample {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelHealthSampleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelHealthSampleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelHealthSample.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelHealthSampleUpsert) {
//			SetBucketTs(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelHealthSampleCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChannelHealthSampleUpsertBulk {
	_c.conflict = opts
	return &ChannelHealthSampleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelHealthSample.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelHealthSampleCreateBulk) OnConflictColumns(columns ...string) *ChannelHealthSampleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelHealthSampleUpsertBulk{
		create: _c,
	}
}

// ChannelHealthSampleUpsertBulk is the builder for "upsert"-ing
// a bulk of ChannelHealthSample nodes.
type ChannelHealthSampleUpsertBulk struct {
	create *ChannelHealthSampleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChannelHealthSample.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(channelhealthsample.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChannelHealthSampleUpsertBulk) UpdateNewValues() *ChannelHealthSampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(channelhealthsample.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(channelhealthsample.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelHealthSample.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChannelHealthSampleUpsertBulk) Ignore() *ChannelHealthSampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelHealthSampleUpsertBulk) DoNothing() *ChannelHealthSampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelHealthSampleCreateBulk.OnConflict
// documentation for more info.
func (u *ChannelHealthSampleUpsertBulk) Update(set func(*ChannelHealthSampleUpsert)) *ChannelHealthSampleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelHealthSampleUpsert{UpdateSet: update})
	}))
	return u
}

// SetBucketTs sets the "bucket_ts" field.
func (u *ChannelHealthSampleUpsertBulk) SetBucketTs(v time.Time) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetBucketTs(v)
	})
}

// UpdateBucketTs sets the "bucket_ts" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertBulk) UpdateBucketTs() *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateBucketTs()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ChannelHealthSampleUpsertBulk) SetAccountID(v int64) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *ChannelHealthSampleUpsertBulk) AddAccountID(v int64) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertBulk) UpdateAccountID() *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ChannelHealthSampleUpsertBulk) SetGroupID(v int64) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *ChannelHealthSampleUpsertBulk) AddGroupID(v int64) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertBulk) UpdateGroupID() *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateGroupID()
	})
}

// SetModel sets the "model" field.
func (u *ChannelHealthSampleUpsertBulk) SetModel(v string) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertBulk) UpdateModel() *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateModel()
	})
}

// SetSuccessCount sets the "success_count" field.
func (u *ChannelHealthSampleUpsertBulk) SetSuccessCount(v int) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetSuccessCount(v)
	})
}

// AddSuccessCount adds v to the "success_count" field.
func (u *ChannelHealthSampleUpsertBulk) AddSuccessCount(v int) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.AddSuccessCount(v)
	})
}

// UpdateSuccessCount sets the "success_count" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertBulk) UpdateSuccessCount() *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateSuccessCount()
	})
}

// SetErrorCount sets the "error_count" field.
func (u *ChannelHealthSampleUpsertBulk) SetErrorCount(v int) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetErrorCount(v)
	})
}

// AddErrorCount adds v to the "error_count" field.
func (u *ChannelHealthSampleUpsertBulk) AddErrorCount(v int) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.AddErrorCount(v)
	})
}

// UpdateErrorCount sets the "error_count" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertBulk) UpdateErrorCount() *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateErrorCount()
	})
}

// SetRateLimitedCount sets the "rate_limited_count" field.
func (u *ChannelHealthSampleUpsertBulk) SetRateLimitedCount(v int) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetRateLimitedCount(v)
	})
}

// AddRateLimitedCount adds v to the "rate_limited_count" field.
func (u *ChannelHealthSampleUpsertBulk) AddRateLimitedCount(v int) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.AddRateLimitedCount(v)
	})
}

// UpdateRateLimitedCount sets the "rate_limited_count" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertBulk) UpdateRateLimitedCount() *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateRateLimitedCount()
	})
}

// SetOverloadedCount sets the "overloaded_count" field.
func (u *ChannelHealthSampleUpsertBulk) SetOverloadedCount(v int) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetOverloadedCount(v)
	})
}

// AddOverloadedCount adds v to the "overloaded_count" field.
func (u *ChannelHealthSampleUpsertBulk) AddOverloadedCount(v int) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.AddOverloadedCount(v)
	})
}

// UpdateOverloadedCount sets the "overloaded_count" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertBulk) UpdateOverloadedCount() *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateOverloadedCount()
	})
}

// SetLatencyP50Ms sets the "latency_p50_ms" field.
func (u *ChannelHealthSampleUpsertBulk) SetLatencyP50Ms(v int) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetLatencyP50Ms(v)
	})
}

// AddLatencyP50Ms adds v to the "latency_p50_ms" field.
func (u *ChannelHealthSampleUpsertBulk) AddLatencyP50Ms(v int) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.AddLatencyP50Ms(v)
	})
}

// UpdateLatencyP50Ms sets the "latency_p50_ms" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertBulk) UpdateLatencyP50Ms() *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateLatencyP50Ms()
	})
}

// SetSource sets the "source" field.
func (u *ChannelHealthSampleUpsertBulk) SetSource(v string) *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ChannelHealthSampleUpsertBulk) UpdateSource() *ChannelHealthSampleUpsertBulk {
	return u.Update(func(s *ChannelHealthSampleUpsert) {
		s.UpdateSource()
	})
}

// Exec executes the query.
func (u *ChannelHealthSampleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChannelHealthSampleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelHealthSampleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelHealthSampleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
