// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelhealthsample"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChannelHealthSampleDelete is the builder for deleting a ChannelHealthSample entity.
type ChannelHealthSampleDelete struct {
	config
	hooks    []Hook
	mutation *ChannelHealthSampleMutation
}

// Where appends a list predicates to the ChannelHealthSampleDelete builder.
func (_d *ChannelHealthSampleDelete) Where(ps ...predicate.ChannelHealthSample) *ChannelHealthSampleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChannelHealthSampleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelHealthSampleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChannelHealthSampleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(channelhealthsample.Table, sqlgraph.NewFieldSpec(channelhealthsample.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChannelHealthSampleDeleteOne is the builder for deleting a single ChannelHealthSample entity.
type ChannelHealthSampleDeleteOne struct {
	_d *ChannelHealthSampleDelete
}

// Where appends a list predicates to the ChannelHealthSampleDelete builder.
func (_d *ChannelHealthSampleDeleteOne) Where(ps ...predicate.ChannelHealthSample) *ChannelHealthSampleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChannelHealthSampleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{channelhealthsample.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelHealthSampleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
