//go:build embed

package web

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/gin-gonic/gin"
)

const (
	// NonceHTMLPlaceholder is the placeholder for nonce in HTML script tags
	NonceHTMLPlaceholder = "__CSP_NONCE_VALUE__"
)

//go:embed all:dist
var frontendFS embed.FS

// PublicSettingsProvider is an interface to fetch public settings
type PublicSettingsProvider interface {
	GetPublicSettingsForInjection(ctx context.Context) (any, error)
}

// FrontendServer serves the embedded frontend with settings injection
type FrontendServer struct {
	distFS      fs.FS
	fileServer  http.Handler
	baseHTML    []byte
	cache       *HTMLCache
	settings    PublicSettingsProvider
	overrideDir string // local file override directory
}

const indexHTMLCacheControl = "no-cache, must-revalidate"

// NewFrontendServer creates a new frontend server with settings injection
func NewFrontendServer(settingsProvider PublicSettingsProvider) (*FrontendServer, error) {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		return nil, err
	}

	// Read base HTML once
	file, err := distFS.Open("index.html")
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()

	baseHTML, err := io.ReadAll(file)
	if err != nil {
		return nil, err
	}

	cache := NewHTMLCache()
	cache.SetBaseHTML(baseHTML)

	return &FrontendServer{
		distFS:      distFS,
		fileServer:  http.FileServer(http.FS(distFS)),
		baseHTML:    baseHTML,
		cache:       cache,
		settings:    settingsProvider,
		overrideDir: filepath.Join("data", "public"),
	}, nil
}

// InvalidateCache invalidates the HTML cache (call when settings change)
func (s *FrontendServer) InvalidateCache() {
	if s != nil && s.cache != nil {
		s.cache.Invalidate()
	}
}

// Middleware returns the Gin middleware handler
func (s *FrontendServer) Middleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		path := c.Request.URL.Path

		if isEmbeddedFrontendMethod(c.Request.Method) && isBlockedRawFrontendPath(c.Request.RequestURI) {
			serveMissingFrontendFallback(c)
			return
		}

		// Skip API routes
		if shouldBypassEmbeddedFrontend(path) || !isEmbeddedFrontendMethod(c.Request.Method) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		// For index.html or SPA routes, serve with injected settings.
		// Missing Vite chunks must remain 404; returning index.html makes browsers
		// try to parse HTML as a JavaScript module and masks deployment/cache issues.
		if cleanPath == "index.html" {
			s.serveIndexHTML(c)
			return
		}
		if !s.fileExists(cleanPath) {
			if isAssetRequest(cleanPath) {
				serveMissingAsset(c)
				return
			}
			if isBlockedFrontendFallbackPath(cleanPath) {
				serveMissingFrontendFallback(c)
				return
			}
			s.serveIndexHTML(c)
			return
		}

		// Try local override first
		if s.tryServeOverride(c, cleanPath) {
			return
		}

		// Serve static files normally
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
	}
}

func (s *FrontendServer) fileExists(path string) bool {
	file, err := s.distFS.Open(path)
	if err != nil {
		return false
	}
	_ = file.Close()
	return true
}

// tryServeOverride checks if a local override file exists and serves it.
// Files in overrideDir take precedence over embedded files.
func (s *FrontendServer) tryServeOverride(c *gin.Context, cleanPath string) bool {
	if s.overrideDir == "" {
		return false
	}
	filePath := filepath.Join(s.overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func (s *FrontendServer) serveIndexHTML(c *gin.Context) {
	// Get nonce from context (generated by SecurityHeaders middleware)
	nonce := middleware.GetNonceFromContext(c)

	// Check cache first
	cached := s.cache.Get()
	if cached != nil {
		// Check If-None-Match for 304 response
		if match := c.GetHeader("If-None-Match"); match == cached.ETag {
			c.Status(http.StatusNotModified)
			c.Abort()
			return
		}

		// Replace nonce placeholder with actual nonce before serving
		content := replaceNoncePlaceholder(cached.Content, nonce)

		c.Header("ETag", cached.ETag)
		c.Header("Cache-Control", indexHTMLCacheControl)
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	// Cache miss - fetch settings and render
	ctx, cancel := context.WithTimeout(c.Request.Context(), 2*time.Second)
	defer cancel()

	type settingsResult struct {
		value any
		err   error
	}
	resultCh := make(chan settingsResult, 1)
	go func() {
		settings, err := s.settings.GetPublicSettingsForInjection(ctx)
		resultCh <- settingsResult{value: settings, err: err}
	}()

	var result settingsResult
	select {
	case result = <-resultCh:
	case <-ctx.Done():
		// The frontend shell should never be blocked by slow public settings
		// reads. Serve the base app and let client-side API calls hydrate.
		s.serveBaseHTMLWithVisitorBootstrap(c, nonce)
		return
	}
	if result.err != nil {
		// Fallback without public settings, but keep the visitor-cookie bootstrap.
		s.serveBaseHTMLWithVisitorBootstrap(c, nonce)
		return
	}

	settingsJSON, err := json.Marshal(result.value)
	if err != nil {
		// Fallback without public settings, but keep the visitor-cookie bootstrap.
		s.serveBaseHTMLWithVisitorBootstrap(c, nonce)
		return
	}

	rendered := s.injectSettings(settingsJSON)
	s.cache.Set(rendered, settingsJSON)

	// Replace nonce placeholder with actual nonce before serving
	content := replaceNoncePlaceholder(rendered, nonce)

	cached = s.cache.Get()
	if cached != nil {
		c.Header("ETag", cached.ETag)
	}
	c.Header("Cache-Control", indexHTMLCacheControl)
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func (s *FrontendServer) serveBaseHTMLWithVisitorBootstrap(c *gin.Context, nonce string) {
	content := injectVisitorCookieBootstrap(s.baseHTML, NonceHTMLPlaceholder)
	content = replaceNoncePlaceholder(content, nonce)
	c.Header("Cache-Control", indexHTMLCacheControl)
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func (s *FrontendServer) injectSettings(settingsJSON []byte) []byte {
	// Create the script tag to inject with nonce placeholder
	// The placeholder will be replaced with actual nonce at request time
	script := []byte(`<script nonce="` + NonceHTMLPlaceholder + `">window.__APP_CONFIG__=` + string(settingsJSON) + `;</script>` + visitorCookieBootstrapScript(NonceHTMLPlaceholder))

	// Inject before </head>
	headClose := []byte("</head>")
	result := bytes.Replace(s.baseHTML, headClose, append(script, headClose...), 1)

	// Replace <title> with custom site name so the browser tab shows it immediately
	result = injectSiteTitle(result, settingsJSON)

	return result
}

// injectSiteTitle replaces the static <title> in HTML with the configured site name.
// This ensures the browser tab shows the correct title before JS executes.
func injectSiteTitle(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteName string `json:"site_name"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil || cfg.SiteName == "" {
		return html
	}

	// Find and replace the existing <title>...</title>
	titleStart := bytes.Index(html, []byte("<title>"))
	titleEnd := bytes.Index(html, []byte("</title>"))
	if titleStart == -1 || titleEnd == -1 || titleEnd <= titleStart {
		return html
	}

	newTitle := []byte("<title>" + cfg.SiteName + " - AI API Gateway</title>")
	var buf bytes.Buffer
	buf.Write(html[:titleStart])
	buf.Write(newTitle)
	buf.Write(html[titleEnd+len("</title>"):])
	return buf.Bytes()
}

// replaceNoncePlaceholder replaces the nonce placeholder with actual nonce value
func replaceNoncePlaceholder(html []byte, nonce string) []byte {
	return bytes.ReplaceAll(html, []byte(NonceHTMLPlaceholder), []byte(nonce))
}

// ServeEmbeddedFrontend returns a middleware for serving embedded frontend
// This is the legacy function for backward compatibility when no settings provider is available
func ServeEmbeddedFrontend() gin.HandlerFunc {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		panic("failed to get dist subdirectory: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(distFS))
	overrideDir := filepath.Join("data", "public")

	return func(c *gin.Context) {
		path := c.Request.URL.Path

		if isEmbeddedFrontendMethod(c.Request.Method) && isBlockedRawFrontendPath(c.Request.RequestURI) {
			serveMissingFrontendFallback(c)
			return
		}

		if shouldBypassEmbeddedFrontend(path) || !isEmbeddedFrontendMethod(c.Request.Method) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		if file, err := distFS.Open(cleanPath); err == nil {
			_ = file.Close()
			// Try local override first
			if tryServeOverrideFile(c, overrideDir, cleanPath) {
				return
			}
			fileServer.ServeHTTP(c.Writer, c.Request)
			c.Abort()
			return
		}
		if isAssetRequest(cleanPath) {
			serveMissingAsset(c)
			return
		}
		if isBlockedFrontendFallbackPath(cleanPath) {
			serveMissingFrontendFallback(c)
			return
		}

		serveIndexHTML(c, distFS)
	}
}

// tryServeOverrideFile is a standalone version of tryServeOverride for legacy usage.
func tryServeOverrideFile(c *gin.Context, overrideDir, cleanPath string) bool {
	if overrideDir == "" {
		return false
	}
	filePath := filepath.Join(overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func isEmbeddedFrontendMethod(method string) bool {
	return method == http.MethodGet || method == http.MethodHead
}

func shouldBypassEmbeddedFrontend(path string) bool {
	trimmed := strings.TrimSpace(path)
	return trimmed == "/api" ||
		strings.HasPrefix(trimmed, "/api/") ||
		strings.HasPrefix(trimmed, "/v1/") ||
		strings.HasPrefix(trimmed, "/v1beta/") ||
		strings.HasPrefix(trimmed, "/backend-api/") ||
		strings.HasPrefix(trimmed, "/openai/") ||
		strings.HasPrefix(trimmed, "/antigravity/") ||
		strings.HasPrefix(trimmed, "/setup/") ||
		trimmed == "/health" ||
		trimmed == "/chat/completions" ||
		trimmed == "/responses" ||
		strings.HasPrefix(trimmed, "/responses/") ||
		strings.HasPrefix(trimmed, "/images/")
}

func isAssetRequest(cleanPath string) bool {
	return strings.HasPrefix(cleanPath, "assets/")
}

func isBlockedFrontendFallbackPath(cleanPath string) bool {
	normalized := strings.Trim(strings.TrimSpace(cleanPath), "/")
	if normalized == "" {
		return false
	}

	lower := strings.ToLower(normalized)
	if strings.Contains(lower, "..") || strings.Contains(lower, "%00") {
		return true
	}

	for _, segment := range strings.Split(lower, "/") {
		if segment == "" {
			continue
		}
		if strings.HasPrefix(segment, ".") {
			return true
		}
	}

	switch lower {
	case "api", "phpmyadmin", "wp-login.php", "wp-config.php":
		return true
	}
	if strings.HasPrefix(lower, "phpmyadmin/") ||
		strings.HasPrefix(lower, "wp-admin/") ||
		strings.HasPrefix(lower, "wp-content/") ||
		strings.HasPrefix(lower, "vendor/") {
		return true
	}

	blockedExts := []string{
		".php", ".asp", ".aspx", ".jsp",
		".sql", ".sqlite", ".db",
		".env", ".ini", ".conf", ".config", ".yaml", ".yml", ".toml",
		".bak", ".backup", ".old", ".orig", ".log",
		".zip", ".tar", ".gz", ".tgz", ".rar", ".7z",
	}
	for _, ext := range blockedExts {
		if strings.HasSuffix(lower, ext) {
			return true
		}
	}
	return false
}

func isBlockedRawFrontendPath(requestURI string) bool {
	raw := strings.ToLower(strings.TrimSpace(requestURI))
	if raw == "" {
		return false
	}
	if idx := strings.IndexByte(raw, '?'); idx >= 0 {
		raw = raw[:idx]
	}
	raw = strings.Trim(raw, "/")
	if raw == "" {
		return false
	}
	if strings.Contains(raw, "\x00") ||
		strings.Contains(raw, "%00") ||
		strings.Contains(raw, "..") ||
		strings.Contains(raw, "%2e") ||
		strings.Contains(raw, "%2f") ||
		strings.Contains(raw, "%5c") ||
		strings.Contains(raw, "etc/passwd") {
		return true
	}
	return false
}

func serveMissingAsset(c *gin.Context) {
	c.Header("Cache-Control", "no-store")
	c.String(http.StatusNotFound, "Asset not found")
	c.Abort()
}

func serveMissingFrontendFallback(c *gin.Context) {
	c.Header("Cache-Control", "no-store")
	c.String(http.StatusNotFound, "404 page not found")
	c.Abort()
}

func serveIndexHTML(c *gin.Context, fsys fs.FS) {
	file, err := fsys.Open("index.html")
	if err != nil {
		c.String(http.StatusNotFound, "Frontend not found")
		c.Abort()
		return
	}
	defer func() { _ = file.Close() }()

	content, err := io.ReadAll(file)
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to read index.html")
		c.Abort()
		return
	}

	nonce := middleware.GetNonceFromContext(c)
	content = injectVisitorCookieBootstrap(content, nonce)
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func injectVisitorCookieBootstrap(html []byte, nonce string) []byte {
	headClose := []byte("</head>")
	script := []byte(visitorCookieBootstrapScript(nonce))
	return bytes.Replace(html, headClose, append(script, headClose...), 1)
}

func visitorCookieBootstrapScript(nonce string) string {
	return `<script nonce="` + nonce + `">
(function(){
  const cookieName = '_xdt_v=';
  function hasVisitorCookie(){ return document.cookie.indexOf(cookieName) !== -1; }
  async function sha256Hex(value){
    const encoded = new TextEncoder().encode(value);
    const hashBuffer = await crypto.subtle.digest('SHA-256', encoded);
    return Array.from(new Uint8Array(hashBuffer)).map(function(b){return b.toString(16).padStart(2,'0');}).join('');
  }
  async function canvasFingerprint(){
    try {
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');
      ctx.textBaseline = 'top';
      ctx.font = '14px Arial';
      ctx.fillText('fingerprint', 2, 2);
      return canvas.toDataURL().slice(-50);
    } catch(e) { return 'no-canvas'; }
  }
  function webglFingerprint(){
    try {
      const canvas = document.createElement('canvas');
      const gl = canvas.getContext('webgl');
      if (!gl) return 'no-webgl';
      const ext = gl.getExtension('WEBGL_debug_renderer_info');
      if (!ext) return 'webgl';
      return String(gl.getParameter(ext.UNMASKED_RENDERER_WEBGL) || 'webgl').slice(0, 30);
    } catch(e) { return 'no-webgl'; }
  }
  async function collectFingerprint(){
    const data = {
      ua: navigator.userAgent,
      lang: navigator.language,
      tz: Intl.DateTimeFormat().resolvedOptions().timeZone,
      screen: screen.width + 'x' + screen.height,
      color: screen.colorDepth,
      hw: navigator.hardwareConcurrency || 0,
      canvas: await canvasFingerprint(),
      webgl: webglFingerprint()
    };
    return sha256Hex(JSON.stringify(data));
  }
  async function issueVisitorCookie(recover){
    if (!window.crypto || !window.crypto.subtle) return;
    const fingerprint = await collectFingerprint();
    const challengeResp = await fetch('/api/public/visitor/challenge' + (recover ? '?recover=1' : ''), {method:'POST', credentials:'same-origin'});
    if (!challengeResp.ok) return;
    const challengeData = await challengeResp.json();
    const prefix = '0'.repeat(challengeData.difficulty || 4);
    let nonce = 0;
    for (;;) {
      const hash = await sha256Hex(challengeData.challenge + nonce);
      if (hash.startsWith(prefix)) break;
      nonce++;
    }
    await fetch('/api/public/visitor/issue-cookie' + (recover ? '?recover=1' : ''), {
      method:'POST',
      credentials:'same-origin',
      headers:{'Content-Type':'application/json'},
      body:JSON.stringify({challenge:challengeData.challenge, nonce:String(nonce), fingerprint:fingerprint})
    });
  }
  if (!hasVisitorCookie()) issueVisitorCookie(false).catch(function(e){ console.error('Visitor cookie issue failed', e); });
  const originalFetch = window.fetch;
  if (originalFetch && !window.__xdtVisitorFetchWrapped) {
    window.__xdtVisitorFetchWrapped = true;
    window.fetch = async function(){
      const response = await originalFetch.apply(this, arguments);
      if (response && response.status === 403) {
        response.clone().json().then(async function(data){
          if (data && data.error === 'cookie reputation too low' && window.confirm('您的访问被暂时限制，点击确定完成验证恢复访问。')) {
            document.cookie = '_xdt_v=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/';
            await issueVisitorCookie(true);
            window.location.reload();
          }
        }).catch(function(){});
      }
      return response;
    };
  }
})();
</script>`
}

func HasEmbeddedFrontend() bool {
	_, err := frontendFS.ReadFile("dist/index.html")
	return err == nil
}
